# Core Status Bar
set -gu status-left
set -gu status-right
set -gu status-justify
set -gu status-style
set -gu status-position

# Window Formats & Separators
set -gu window-status-style
set -gu window-status-current-style
set -gu window-status-format
set -gu window-status-current-format
set -gu window-status-separator

# Panes & Prompts
set -gu pane-border-style
set -gu pane-active-border-style
set -gu message-style
set -gu message-command-style
set -gu mode-style